MCMS/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
    path('auth/',include('Users.urls'))
    
]

if settings.DEBUG :
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('review.urls')),
]

dtl/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dtl_app.urls'))
]

lms/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('authors/', include('authors.urls')),
    path('',include('inheritance.urls')),
    
]

lms/authors/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
     first_name=models.CharField(max_length=100)
     last_name= models.CharField(max_length=100)
     birth_date=models.DateField()
     
     def __str__(self):
         return f"{self.first_name} {self.last_name}"

lms/library/models.py
from django.db import models
from authors.models import Author


# Create your models here.
class Book(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    number_of_pages = models.PositiveIntegerField()
    published_on = models.DateField()

    def __str__(self):
        return f"{self.title} by {self.author}"

dtl_url_static/lms/authors/views.py
from django.shortcuts import render

# Create your views here.

def all_authors(request):
    return render(request, "authors/authors.html")

def book_signings(request):
    return render(request, "authors/book-signings.html")

dtl_url_static/lms/inheritance/views.py
from django.shortcuts import render

# Create your views here.
def demo_inheritance(request):
    return render(request, "inheritance/demo.html", {"topic": "Template Inheritance"})

dtl_url_static/lms/inheritance_correction/views.py
from django.shortcuts import render

# Create your views here.
def demo_inheritance(request):
    return render(request, "inheritance_correction/demo.html")

dtl_url_static/lms/library/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render(request, "library/home.html")

def book_list(request):
    return render(request, "library/list-of-books.html")

dtl_url_static/lms/pages/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "pages/home.html")

def about(request):
    return render(request, "pages/about.html")

def contact(request):
    return render(request, "pages/contact.html")

lms/authors/views.py
from django.shortcuts import render

# Create your views here.
from .models import Author
from library.models import Book
from django.http import HttpResponse


def all_authors(request):
    return render(request, "author/authors.html")


def book_signings(request):
    return render(request, "author/booksignings.html")


def mvt(request):
    authors = Author.objects.all()
    authors_ordered_by_birth_date = authors.order_by("birth_date")
    books = Book.objects.order_by("-title")
    context = {
        "authors_dob": authors_ordered_by_birth_date,
        "authors": authors,
        "books": books,
    }
    return render(request, "author/mvt.html", context)

lms/inheritance/views.py
from django.shortcuts import render

# Create your views here.
def demo_inheritance(request):
    return render(request,'inherit/demo.html')

lms/library/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
    return render(request,'library/home.html')

def book_list(request):
    return render(request,'library/books.html')

lms/templates/author/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="color: blue;">List of all authors</h1>
    
</body>
</html>

lms/templates/author/booksignings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="border: 2px solid black;">Upcoming book signings</h1>
</body>
</html>

lms/templates/author/mvt.html
{% extends "partials/base.html" %}
{% block content %}
<h1>Authors ordered by date of birth</h1>
     {% for author in authors_dob %}
          <h2>first Name</h2>
          <p>{{ author.first_name }}</p>
          <h3>Last Name</h3>
          <p>{{ author.last_name }}</p>
          <h3>Date of birth</h3>
          <p>{{ author.birth_date }}</p>
     {% endfor %}
     <h1>Authors ordered in default order</h1>
     {% for author in authors %}
          <h2>first Name</h2>
          <p>{{ author.first_name }}</p>
          <h3>Last Name</h3>
          <p>{{ author.last_name }}</p>
          <h3>Date of birth</h3>
          <p>{{ author.birth_date }}</p>
     {% endfor %}
     {% for book in books %}
          <h3>Book title : {{ book.title }}  by {{ book.author }}</h3>
          <h3>published date : {{ book.published_on }}</h3>
     {% endfor %}

{% for author in authors %}
    {% for book in author.book_set.all %}
       <h2> {{ author }}</h2>
       <p>{{ book }}</p>
    {% endfor %}
{% endfor %}
{% endblock content %}